/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/routes/__root'
import { Route as WarehouseDashboardImport } from './app/routes/warehouse/warehouseDashboard'
import { Route as RouterImport } from './app/routes/router'
import { Route as ClientDashboardImport } from './app/routes/customer/custumerDashboard'

// Create/Update Routes

const WarehouseDashboardRoute = WarehouseDashboardImport.update({
  id: '/warehouseDashboard',
  path: '/warehouseDashboard',
  getParentRoute: () => rootRoute,
} as any)

const RouterRoute = RouterImport.update({
  id: '/router',
  path: '/router',
  getParentRoute: () => rootRoute,
} as any)

const ClientDashboardRoute = ClientDashboardImport.update({
  id: '/clientDashboard',
  path: '/clientDashboard',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clientDashboard': {
      id: '/clientDashboard'
      path: '/clientDashboard'
      fullPath: '/clientDashboard'
      preLoaderRoute: typeof ClientDashboardImport
      parentRoute: typeof rootRoute
    }
    '/router': {
      id: '/router'
      path: '/router'
      fullPath: '/router'
      preLoaderRoute: typeof RouterImport
      parentRoute: typeof rootRoute
    }
    '/warehouseDashboard': {
      id: '/warehouseDashboard'
      path: '/warehouseDashboard'
      fullPath: '/warehouseDashboard'
      preLoaderRoute: typeof WarehouseDashboardImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/clientDashboard': typeof ClientDashboardRoute
  '/router': typeof RouterRoute
  '/warehouseDashboard': typeof WarehouseDashboardRoute
}

export interface FileRoutesByTo {
  '/clientDashboard': typeof ClientDashboardRoute
  '/router': typeof RouterRoute
  '/warehouseDashboard': typeof WarehouseDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/clientDashboard': typeof ClientDashboardRoute
  '/router': typeof RouterRoute
  '/warehouseDashboard': typeof WarehouseDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/clientDashboard' | '/router' | '/warehouseDashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/clientDashboard' | '/router' | '/warehouseDashboard'
  id: '__root__' | '/clientDashboard' | '/router' | '/warehouseDashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ClientDashboardRoute: typeof ClientDashboardRoute
  RouterRoute: typeof RouterRoute
  WarehouseDashboardRoute: typeof WarehouseDashboardRoute
}

const rootRouteChildren: RootRouteChildren = {
  ClientDashboardRoute: ClientDashboardRoute,
  RouterRoute: RouterRoute,
  WarehouseDashboardRoute: WarehouseDashboardRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/clientDashboard",
        "/router",
        "/warehouseDashboard"
      ]
    },
    "/clientDashboard": {
      "filePath": "clientDashboard.tsx"
    },
    "/router": {
      "filePath": "router.ts"
    },
    "/warehouseDashboard": {
      "filePath": "warehouseDashboard.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
